class DeviceChoices:

    models = [
        "local",
        "Google Pixel 4 XL",
        "Google Pixel 4",
        "Google Pixel 3a XL",
        "Google Pixel 3a",
        "Google Pixel 3 XL",
        "Google Pixel 3",
        "Google Pixel 2",
        "Google Pixel",
        "Google Nexus 6",
        "Google Nexus 5",
        "iPhone 12 Pro Max",
        "iPhone 12 Pro",
        "iPhone 12",
        "iPhone 11 Pro Max",
        "iPhone 11 Pro",
        "iPhone 11",
        "iPhone XS Max",
        "iPhone XS",
        "iPhone XR",
        "iPhone X",
        "iPhone 8 Plus",
        "iPhone 8",
        "iPhone 7 Plus",
        "iPhone 7",
        "iPhone 6S Plus",
        "iPhone 6S",
        "iPhone 6",
        "iPhone SE 2020",
        "iPhone SE",
        "iPad",
        "iPad Pro 12.9 2020",
        "iPad Pro 12.9 2018",
        "iPad Pro 11 2020",
        "iPad Mini 2019",
        "iPad Air 2019",
        "iPad 7th",
        "iPad Pro 11 2018",
        "iPad Pro 9.7 2016",
        "iPad Pro 12.9 2017",
        "iPad Mini 4",
        "iPad 6th",
        "iPad 5th",
        "Motorola Moto G7 Play",
        "Motorola Moto X 2nd Gen",
        "Motorola Moto X 2nd Gen",
        "OnePlus 8",
        "OnePlus 7",
        "OnePlus 7T",
        "OnePlus 6T",
        "Samsung Galaxy S20",
        "Samsung Galaxy S20 Plus",
        "Samsung Galaxy S20 Ultra",
        "Samsung Galaxy Note 20 Ultra",
        "Samsung Galaxy Note 20",
        "Samsung Galaxy Note 10 Plus",
        "Samsung Galaxy Note 10",
        "Samsung Galaxy Note 9",
        "Samsung Galaxy Note 8",
        "Samsung Galaxy Note 4",
        "Samsung Galaxy A51",
        "Samsung Galaxy A11",
        "Samsung Galaxy A10",
        "Samsung Galaxy S10e",
        "Samsung Galaxy S10 Plus",
        "Samsung Galaxy S10",
        "Samsung Galaxy S9 Plus",
        "Samsung Galaxy S9",
        "Samsung Galaxy S8 Plus",
        "Samsung Galaxy S8",
        "Samsung Galaxy S7",
        "Samsung Galaxy S6",
        "Samsung Galaxy J7 Prime",
        "Samsung Galaxy Tab S6",
        "Samsung Galaxy Tab S5e",
        "Samsung Galaxy Tab S4",
        "Samsung Galaxy Tab S3",
        "Samsung Galaxy Tab 4",
        "Vivo Y50",
        "Xiaomi Redmi Note 8",
        "Xiaomi Redmi Note 7",
    ]
